/// Flutter icons Rshb
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Rshb
///      fonts:
///       - asset: fonts/Rshb.ttf
///
///
///

// Flutter imports:
import 'package:flutter/widgets.dart';

class RshbIcons {
  RshbIcons._();

  static const _kFontFam = 'rshb';
  static const _kFontPkg = null;

  static const IconData bookmark_active =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bread =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eggs =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meat =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vegetables =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
